[package]
name = "hard-link-dedup"
version = "0.1.0"
authors = ["Marcus Ofenhed"]
edition = "2021"
license = "MIT OR Apache-2.0"
categories = ["filesystem", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
